# Generated by Django 4.0.5 on 2022-06-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_survey_wav_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfPatient_text', models.CharField(blank=True, max_length=1024, null=True)),
                ('diagnosis_text', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(blank=True, max_length=1024, null=True)),
                ('pesel_int', models.IntegerField()),
                ('disease_text', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='survey',
            name='wav_file',
            field=models.FileField(blank=True, null=True, upload_to='wav_files'),
        ),
    ]
