# Generated by Django 4.0.5 on 2022-06-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_diagnosis_patient2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='patient',
            new_name='Doctor',
        ),
    ]
