# Generated by Django 4.0.5 on 2022-06-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_rename_patient_diagnosis_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='patient2',
            new_name='patient',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='nameOfPatient_text',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='disease_text',
        ),
    ]
