# Generated by Django 4.0.5 on 2022-06-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_rename_patient2_diagnosis_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='patient',
            new_name='Patient',
        ),
    ]
